# Permalinks
permalink:           pretty

# Setup
title:               Ao Xinyan
tagline:             一个初级 coder 的学习日记
url:                 http://theaao.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ao Xinyan
  url:               
  email:             ao_xinyan@163.com

# Custom vars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
